[package]
name = "spectral_norm6_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.8.0"
num_cpus = "1.16.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
