[package]
name = "regex_redux2_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
pcre2 = "0.2.6"
rayon = "1.8.0"

# Enable SIMD optimizations where possible
[features]
simd-accel = []

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
