c:
	gcc -O3 -I/usr/include/apr-1.0 *.c -lm -lapr-1

rust:
	cd binary_trees_rust; cargo build --release

run-c:
	./a.out 21

run-rust:
	./binary_trees_rust/target/release/binary_trees_rust 21

run-python:
	python3 binary-trees2.py 21
