[package]
name = "fasta"
version = "0.1.0"
edition = "2021"
authors = ["Claude"]

# Define multiple binaries for different implementations
[[bin]]
name = "fasta"
path = "src/fasta.rs"

[[bin]]
name = "fasta_optimized"
path = "src/fasta_optimized.rs"

[dependencies]
# No external dependencies required

# Optimization settings for release builds
[profile.release]
opt-level = 3             # Maximum optimization
lto = true                # Link-time optimization
codegen-units = 1         # Single-unit optimization
panic = "abort"           # Smaller code size by not unwinding on panics