[package]
name = "photometry_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rustfft = "6.1.0"
num-complex = "0.4.3"
rayon = "1.7.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
