#c:
#	gcc -O3 -fopenmp -march=native *.c -lm

#rust:
#	cd mandelbrot7_rust; cargo build --release

#run-c:
#	./a.out 16000

#run-rust:
#	./mandelbrot7_rust/target/release/mandelbrot7_rust 16000

run-python:
	python3 mandelbrot7.py 16000
